np.sort()

In [1]:
import numpy as np
a = np.random.randint(1,100,15)
np.sort(a)[::-1]

array([91, 82, 81, 78, 73, 70, 68, 68, 64, 39, 35, 35, 31, 25,  3])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
np.sort(b,axis=0)

array([[ 1,  5, 24,  1],
       [ 4, 20, 33, 19],
       [13, 23, 53, 42],
       [36, 44, 74, 52],
       [89, 70, 81, 62],
       [94, 93, 97, 74]])

np.append() : appends values along the mentioned axis at the end of the array

In [3]:
np.append(a,200)

array([ 70,  81,  25,  39,  64,  68,  31,  91,  35,   3,  35,  68,  78,
        73,  82, 200])

np.concatenate()

In [4]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
np.concatenate((c,d),axis=0)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

np.unique()

In [5]:
e = np.array([1,1,2,2,3,4,3,5,5,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

np.expand_dims

In [6]:
np.expand_dims(a,axis=0)

array([[70, 81, 25, 39, 64, 68, 31, 91, 35,  3, 35, 68, 78, 73, 82]])

np.where : return the indices of the element in an input where the given condition is satisfied

In [7]:
#find all the indices where a is greater than 50
np.where(a>50)

(array([ 0,  1,  4,  5,  7, 11, 12, 13, 14], dtype=int64),)

In [8]:
#replce all the value greater than 50 with 0
np.where(a>50,0,a)

array([ 0,  0, 25, 39,  0,  0, 31,  0, 35,  3, 35,  0,  0,  0,  0])

np.argmax : returns indices of the max element of the array in a particular axis

In [9]:
np.argmax(a)

7

In [10]:
np.argmin(a)


9

np.cumsum : when we want to compute the cummulative sum of array elements over a given axis

In [11]:
np.cumsum(a)

array([ 70, 151, 176, 215, 279, 347, 378, 469, 504, 507, 542, 610, 688,
       761, 843])

In [12]:
#np.cumprod
np.cumprod(a)

array([         70,        5670,      141750,     5528250,   353808000,
       -1710859776, -1497045504,  1207812608,  -676231680, -2028695040,
        2010117632,  -750954496,  1555091456,  1852526592,  1583325184])

np.percentile : used to compute the nth percentile of the given data along the specified axis


In [13]:
np.percentile(a,0)

3.0

np.histogram : represents the frequency of data distribution in the graphical form


In [15]:
np.histogram(a,bins=[0,50,100])

(array([6, 9], dtype=int64), array([  0,  50, 100]))

np.corrcoef : return pearson product-moment correlation coefficient

In [16]:
salary = np.array([20000,40000,25000,35000,50000])
experience = np.array([1,3,2,4,2])
np.corrcoef(salary,experience)

array([[1.       , 0.4040951],
       [0.4040951, 1.       ]])

np.isin : we can see that one array having values are checked in different numpy array having diffn elements with diffn sizes

In [21]:
a
items = [10,20,30,40,50,60,70,80,90]
a[np.isin(a,items)]


array([70])

np.flip : reverse the order of an array elements along the specified axis preserving the shape of array

In [25]:
np.flip(a)

array([82, 73, 78, 68, 35,  3, 35, 91, 31, 68, 64, 39, 25, 81, 70])

In [26]:
a

array([70, 81, 25, 39, 64, 68, 31, 91, 35,  3, 35, 68, 78, 73, 82])